import os
from datetime import datetime

def publish_article(title, content):
    # تنسيق التاريخ والاسم للملفات (متطلب أساسي لـ Jekyll)
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{date_str}-{title.lower().replace(' ', '-')}.md"
    filepath = os.path.join("_posts", filename)
    
    # تنسيق محتوى المقال مع الـ Front Matter (مهم جداً لـ Jekyll)
    full_content = f"---\nlayout: post\ntitle: {title}\n---\n\n{content}"
    
    # كتابة الملف داخل مجلد _posts
    with open(filepath, "w") as f:
        f.write(full_content)
    
    # الرفع التلقائي
    os.system("git add .")
    os.system(f'git commit -m "Automated publish: {title}"')
    os.system("git push origin main")
    print(f"Article '{title}' published successfully in English!")

# مثال للاستخدام من قبل الوكلاء الآخرين:
if __name__ == "__main__":
    publish_article("My First AI Post", "This is an automated post generated by Dobli Agent in English.")
